version: '3.8'

services:
  customer_retention:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: nexus_customer_retention
    ports:
      - "8000:8000"
    command: ["uvicorn", "1_Customer_Retention.app.api.customer360_router:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./datasets:/app/datasets
      - ./1_Customer_Retention:/app/1_Customer_Retention

  anomaly_detection:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: nexus_anomaly_detection
    ports:
      - "8001:8001"
    command: ["uvicorn", "2_Anomaly_Detection.app.api.logistics_forecast_router:app", "--host", "0.0.0.0", "--port", "8001"]
    volumes:
      - ./datasets:/app/datasets
      - ./2_Anomaly_Detection:/app/2_Anomaly_Detection

  predictive_maintenance:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: nexus_predictive_maintenance
    ports:
      - "8002:8002"
    command: ["uvicorn", "3_Predictive_Intelligence.app.api.maintenance_router:app", "--host", "0.0.0.0", "--port", "8002"]
    volumes:
      - ./datasets:/app/datasets
      - ./3_Predictive_Intelligence:/app/3_Predictive_Intelligence

  decision_engine:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: nexus_decision_engine
    ports:
      - "8003:8003"
    command: ["uvicorn", "4_Decision_Making.app.api.insurance_5model_router:app", "--host", "0.0.0.0", "--port", "8003"]
    volumes:
      - ./datasets:/app/datasets
      - ./4_Decision_Making:/app/4_Decision_Making
